### ISSUE TITLE
Retrieval Works But Doesn't Remember Previous Messages

### ISSUE THREAD

**Issue by Jakisundays** [langchain-ai/langchain-nextjs-template#1]
I've seen something curious in my code. While the retrieval process appears fine, the model doesn't recall past chat messages. This is leading to unexpected results in the conversation.

Here's what's happening: The model's replies don't consider the earlier messages, treating each one separately. This behavior is not just in my code but also on the demo website.

<img width="651" alt="Screen Shot 2023-08-27 at 8 45 08 PM" src="https://github.com/langchain-ai/langchain-nextjs-template/assets/63080134/7a518b80-aab5-4421-985a-7df4fdfd6b3d">

**Comment by jacoblee93** [comment]
The existing prompt isn't great at answering meta-questions about the conversation history (it's more for dereferencing references to entities in previously asked questions).

Will look into adding a better example!

**Comment by jacoblee93** [comment]
I've made some changes that should make the chain better account for history by passing the history through into the final generation:

https://github.com/langchain-ai/langchain-nextjs-template/blob/main/app/api/chat/retrieval/route.ts#L112

**Comment by Jakisundays** [comment]
You are the goat 🐐 @jacoblee93
