### ISSUE TITLE
Why should wait for 300 seconds?

### ISSUE THREAD

**Issue by sunghyunzz** [langchain-ai/langchain-nextjs-template#15]
Thank you for providing a good example. Reviewing the code has been very helpful. However, while examining the code, I came across a section where it waits for 300 seconds if there are no messages. I'm curious why this behavior is included and if there are any specific considerations to be aware of.

https://github.com/langchain-ai/langchain-nextjs-template/blob/d6ef6dc4a8aca73679474164c69ea209bf3fbdc1/components/ChatWindow.tsx#L58-L68

**Comment by jacoblee93** [comment]
300 milliseconds, not 300 seconds! And I think it's a hacky way to ensure that the message input sliding animation that happens on first message finishes.

**Comment by sunghyunzz** [comment]
> 300 milliseconds, not 300 seconds!

Oops, my bad 😅

> it's a hacky way to ensure that the message input sliding animation that happens on first message finishes.

I see, thanks for clearing that up!
