### ISSUE TITLE
how to create a chat application using the bedrock llama 2 model in the starter template

### ISSUE THREAD

**Issue by raksrivastava** [langchain-ai/langchain-nextjs-template#18]
how to create a chat application using the bedrock llama 2 model in the starter template (LangChain + Next.js Starter Template)

**Comment by jacoblee93** [comment]
Here is one app that shows this - it uses Llama 2 with Cloudflare Workers AI by default but also can use Bedrock:

https://github.com/langchain-ai/langchain-cloudflare-nuxt-template
