### ISSUE TITLE
Source does not return in UTF-8

### ISSUE THREAD

**Issue by felipeotarola** [langchain-ai/langchain-nextjs-template#20]
the text that are displayed as source is not rendered in UTF8
All of the rest of the text is correctly formatted,

![image](https://github.com/langchain-ai/langchain-nextjs-template/assets/5517674/35af1aa5-fb35-4bec-aae0-399df7736f7a)

I have added
"Content-Type": "application/json; charset=utf-8", 
to the StreamingTextResponse in retrival/route but that didn't help, 

Any ideas?

**Comment by jacoblee93** [comment]
I think doing this on the frontend may fix it?

**Comment by AlexBSoft** [comment]
To fix that at `components/ChatWindow.tsx` line `45` you need to replace `atob(sourcesHeader)` with `(Buffer.from(sourcesHeader, 'base64')).toString('utf8')`

The problem with atob function

**Comment by jacoblee93** [comment]
Would you be up for opening a PR?

**Comment by felipeotarola** [comment]
@AlexBSoft  Perfect, this was a nice solution, I build an entire function lto make it work :D.

  function base64Decode(str:any) {
    return decodeURIComponent(Array.prototype.map.call(atob(str), function(c) {
      return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));
  }
