### ISSUE TITLE
Why is custom Chain used instead of Langchain's chain

### ISSUE THREAD

**Issue by 4N1Z** [langchain-ai/langchain-nextjs-template#3]
I have been playing with the code, and found out that instead of using Langchain's chain it uses custom chain

```
type ConversationalRetrievalQAChainInput = {
  question: string;
  chat_history: VercelChatMessage[];
};

```

Why is it  ?

**Comment by jacoblee93** [comment]
We're generally moving examples to expression language as it's easier to customize and understand what's going on under the hood:

https://js.langchain.com/docs/expression_language/
