### ISSUE TITLE
Anyone knows how to make it return source documents?

### ISSUE THREAD

**Issue by evanyang0202** [langchain-ai/langchain-nextjs-template#6]

**Comment by jacoblee93** [comment]
I've made some updates to make the QA chain retrieval return documents via header - try it out!

https://github.com/langchain-ai/langchain-nextjs-template/blob/main/app/api/chat/retrieval/route.ts#L112

**Comment by benedictbihl** [comment]
Hi @jacoblee93 i just tried your example in an attempt to work around the issue i am having with `handleRetrieverEnd` not containing the documents when running as vercel serverless function but i run into the same problem here. I opened this issue over at langchainjs and would appreciate it if you can take a look https://github.com/langchain-ai/langchainjs/issues/3569

Thanks!
