### ISSUE TITLE
Integrating Vercel KV With LangChain Stream 

### ISSUE THREAD

**Issue by scottklein7** [langchain-ai/langchain-nextjs-template#7]
Howdy All,

I could use some guidance here, as I am trying to integrate the callback feature from "ai" that allows you to write the data to you KV database. 

Essentially I am trying to integrate these two blocks of code. The latter block comes from Vercels starter next ai app. Any help would be great!

`const chain = prompt.pipe(model).pipe(outputParser)

  const stream = await chain.stream({
    chat_history: formattedPreviousMessages.join('\n'),
    input: currentMessageContent
  })

  const stream = OpenAIStream(res, {
    async onCompletion(completion) {
      const title = json.messages[0].content.substring(0, 100)
      const id = json.id ?? nanoid()
      const createdAt = Date.now()
      const path = `/chat/${id}`
      const payload = {
        id,
        title,
        userId: `uid-${userId}`,
        createdAt,
        path,
        messages: [
          ...messages,
          {
            content: completion,
            role: 'assistant'
          }
        ]
      }
      console.log(payload)
      await kv.hmset(`chat:${id}`, payload)
      await kv.zadd(`user:chat:${userId}`, {
        score: createdAt,
        member: `chat:${id}`
      })
    }
  })`

**Comment by fro35i** [comment]
@scottklein7 did you find a solution? Or different approach of a chain callback?

**Comment by scottklein7** [comment]
No I am having trouble with this one... I want to use the next template, but use langchain, kv, and pinecone but cant find much out there
